#!/bin/bash

# SECURE SETTINGS.PHP
# ------------------------------------------------------------------------------------------------ #

chmod 644 sites/default/settings.php


# OPTIMIZATIONS
# ------------------------------------------------------------------------------------------------ #
echo "Put the following in settings.php and then continue"
echo ""
echo "ini_set('max_execution_time', 90);"
echo "ini_set('memory_limit', '128M');"
echo "ini_set('max_input_nesting_level', 64);"
echo "ini_set('max_execution_time', 90);"
echo "ini_set('post_max_size', '128M');"
echo "ini_set('upload_max_filesize', '64M');"
echo ""
read -p "Continue? (y/n): " -n 1
echo ""
if [[ $REPLY =~ ^[Nn]$ ]]
then
  exit 1
fi

# DISABLE SOME CORE MODULES
# ------------------------------------------------------------------------------------------------ #
drush dis –y dashboard, dblog, update # for performance reasons
drush dis –y overlay # not compatible with Flash videos at the moment
drush dis -y contextual # Contextual Links is annoying

# ADMIN
# ------------------------------------------------------------------------------------------------ #
drush en -y admin_menu admin_menu_toolbar

# SITE BUILDING
# ------------------------------------------------------------------------------------------------ #
drush en -y ctools
drush dis -y ctools_ajax_sample, ctools_plugin_example, advanced_help
drush en -y views
drush en -y panels

# CONTENT MANAGEMENT
# ------------------------------------------------------------------------------------------------ #
drush en -y imce imce_wysiwyg wysiwyg

# THEMING
# ------------------------------------------------------------------------------------------------ #
echo "THEMING"
echo "Don't forget to make a screenshot.png for your theme - 294x219px"